// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sessions

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockManager creates a new instance of MockManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManager {
	mock := &MockManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockManager is an autogenerated mock type for the Manager type
type MockManager struct {
	mock.Mock
}

type MockManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManager) EXPECT() *MockManager_Expecter {
	return &MockManager_Expecter{mock: &_m.Mock}
}

// CleanUpExpiredSessions provides a mock function for the type MockManager
func (_mock *MockManager) CleanUpExpiredSessions(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// MockManager_CleanUpExpiredSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CleanUpExpiredSessions'
type MockManager_CleanUpExpiredSessions_Call struct {
	*mock.Call
}

// CleanUpExpiredSessions is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockManager_Expecter) CleanUpExpiredSessions(ctx interface{}) *MockManager_CleanUpExpiredSessions_Call {
	return &MockManager_CleanUpExpiredSessions_Call{Call: _e.mock.On("CleanUpExpiredSessions", ctx)}
}

func (_c *MockManager_CleanUpExpiredSessions_Call) Run(run func(ctx context.Context)) *MockManager_CleanUpExpiredSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManager_CleanUpExpiredSessions_Call) Return() *MockManager_CleanUpExpiredSessions_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockManager_CleanUpExpiredSessions_Call) RunAndReturn(run func(ctx context.Context)) *MockManager_CleanUpExpiredSessions_Call {
	_c.Run(run)
	return _c
}

// GetSession provides a mock function for the type MockManager
func (_mock *MockManager) GetSession(ctx context.Context, token string) PrincipalClaims {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for GetSession")
	}

	var r0 PrincipalClaims
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) PrincipalClaims); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Get(0).(PrincipalClaims)
	}
	return r0
}

// MockManager_GetSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSession'
type MockManager_GetSession_Call struct {
	*mock.Call
}

// GetSession is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockManager_Expecter) GetSession(ctx interface{}, token interface{}) *MockManager_GetSession_Call {
	return &MockManager_GetSession_Call{Call: _e.mock.On("GetSession", ctx, token)}
}

func (_c *MockManager_GetSession_Call) Run(run func(ctx context.Context, token string)) *MockManager_GetSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockManager_GetSession_Call) Return(principalClaims PrincipalClaims) *MockManager_GetSession_Call {
	_c.Call.Return(principalClaims)
	return _c
}

func (_c *MockManager_GetSession_Call) RunAndReturn(run func(ctx context.Context, token string) PrincipalClaims) *MockManager_GetSession_Call {
	_c.Call.Return(run)
	return _c
}

// NewSession provides a mock function for the type MockManager
func (_mock *MockManager) NewSession(ctx context.Context, data PrincipalClaims, validForDuration time.Duration) (string, bool) {
	ret := _mock.Called(ctx, data, validForDuration)

	if len(ret) == 0 {
		panic("no return value specified for NewSession")
	}

	var r0 string
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, PrincipalClaims, time.Duration) (string, bool)); ok {
		return returnFunc(ctx, data, validForDuration)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, PrincipalClaims, time.Duration) string); ok {
		r0 = returnFunc(ctx, data, validForDuration)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, PrincipalClaims, time.Duration) bool); ok {
		r1 = returnFunc(ctx, data, validForDuration)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockManager_NewSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewSession'
type MockManager_NewSession_Call struct {
	*mock.Call
}

// NewSession is a helper method to define mock.On call
//   - ctx context.Context
//   - data PrincipalClaims
//   - validForDuration time.Duration
func (_e *MockManager_Expecter) NewSession(ctx interface{}, data interface{}, validForDuration interface{}) *MockManager_NewSession_Call {
	return &MockManager_NewSession_Call{Call: _e.mock.On("NewSession", ctx, data, validForDuration)}
}

func (_c *MockManager_NewSession_Call) Run(run func(ctx context.Context, data PrincipalClaims, validForDuration time.Duration)) *MockManager_NewSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 PrincipalClaims
		if args[1] != nil {
			arg1 = args[1].(PrincipalClaims)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockManager_NewSession_Call) Return(s string, b bool) *MockManager_NewSession_Call {
	_c.Call.Return(s, b)
	return _c
}

func (_c *MockManager_NewSession_Call) RunAndReturn(run func(ctx context.Context, data PrincipalClaims, validForDuration time.Duration) (string, bool)) *MockManager_NewSession_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveSession provides a mock function for the type MockManager
func (_mock *MockManager) RemoveSession(ctx context.Context, token string) bool {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for RemoveSession")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockManager_RemoveSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveSession'
type MockManager_RemoveSession_Call struct {
	*mock.Call
}

// RemoveSession is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockManager_Expecter) RemoveSession(ctx interface{}, token interface{}) *MockManager_RemoveSession_Call {
	return &MockManager_RemoveSession_Call{Call: _e.mock.On("RemoveSession", ctx, token)}
}

func (_c *MockManager_RemoveSession_Call) Run(run func(ctx context.Context, token string)) *MockManager_RemoveSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockManager_RemoveSession_Call) Return(b bool) *MockManager_RemoveSession_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockManager_RemoveSession_Call) RunAndReturn(run func(ctx context.Context, token string) bool) *MockManager_RemoveSession_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockStorage
func (_mock *MockStorage) Get(ctx context.Context, hashedToken string) (PrincipalClaims, error) {
	ret := _mock.Called(ctx, hashedToken)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 PrincipalClaims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (PrincipalClaims, error)); ok {
		return returnFunc(ctx, hashedToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) PrincipalClaims); ok {
		r0 = returnFunc(ctx, hashedToken)
	} else {
		r0 = ret.Get(0).(PrincipalClaims)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, hashedToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockStorage_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - hashedToken string
func (_e *MockStorage_Expecter) Get(ctx interface{}, hashedToken interface{}) *MockStorage_Get_Call {
	return &MockStorage_Get_Call{Call: _e.mock.On("Get", ctx, hashedToken)}
}

func (_c *MockStorage_Get_Call) Run(run func(ctx context.Context, hashedToken string)) *MockStorage_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_Get_Call) Return(principalClaims PrincipalClaims, err error) *MockStorage_Get_Call {
	_c.Call.Return(principalClaims, err)
	return _c
}

func (_c *MockStorage_Get_Call) RunAndReturn(run func(ctx context.Context, hashedToken string) (PrincipalClaims, error)) *MockStorage_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type MockStorage
func (_mock *MockStorage) Remove(ctx context.Context, hashedToken string) error {
	ret := _mock.Called(ctx, hashedToken)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, hashedToken)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockStorage_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
//   - hashedToken string
func (_e *MockStorage_Expecter) Remove(ctx interface{}, hashedToken interface{}) *MockStorage_Remove_Call {
	return &MockStorage_Remove_Call{Call: _e.mock.On("Remove", ctx, hashedToken)}
}

func (_c *MockStorage_Remove_Call) Run(run func(ctx context.Context, hashedToken string)) *MockStorage_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_Remove_Call) Return(err error) *MockStorage_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_Remove_Call) RunAndReturn(run func(ctx context.Context, hashedToken string) error) *MockStorage_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockStorage
func (_mock *MockStorage) Set(ctx context.Context, hashedToken string, claims PrincipalClaims, expiresAt time.Time) error {
	ret := _mock.Called(ctx, hashedToken, claims, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, PrincipalClaims, time.Time) error); ok {
		r0 = returnFunc(ctx, hashedToken, claims, expiresAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockStorage_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - hashedToken string
//   - claims PrincipalClaims
//   - expiresAt time.Time
func (_e *MockStorage_Expecter) Set(ctx interface{}, hashedToken interface{}, claims interface{}, expiresAt interface{}) *MockStorage_Set_Call {
	return &MockStorage_Set_Call{Call: _e.mock.On("Set", ctx, hashedToken, claims, expiresAt)}
}

func (_c *MockStorage_Set_Call) Run(run func(ctx context.Context, hashedToken string, claims PrincipalClaims, expiresAt time.Time)) *MockStorage_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 PrincipalClaims
		if args[2] != nil {
			arg2 = args[2].(PrincipalClaims)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStorage_Set_Call) Return(err error) *MockStorage_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_Set_Call) RunAndReturn(run func(ctx context.Context, hashedToken string, claims PrincipalClaims, expiresAt time.Time) error) *MockStorage_Set_Call {
	_c.Call.Return(run)
	return _c
}
