// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sessions

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// GetSession provides a mock function for the type MockService
func (_mock *MockService) GetSession(ctx context.Context, token string) *AuthClaims {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for GetSession")
	}

	var r0 *AuthClaims
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *AuthClaims); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*AuthClaims)
		}
	}
	return r0
}

// MockService_GetSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSession'
type MockService_GetSession_Call struct {
	*mock.Call
}

// GetSession is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockService_Expecter) GetSession(ctx interface{}, token interface{}) *MockService_GetSession_Call {
	return &MockService_GetSession_Call{Call: _e.mock.On("GetSession", ctx, token)}
}

func (_c *MockService_GetSession_Call) Run(run func(ctx context.Context, token string)) *MockService_GetSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetSession_Call) Return(authClaims *AuthClaims) *MockService_GetSession_Call {
	_c.Call.Return(authClaims)
	return _c
}

func (_c *MockService_GetSession_Call) RunAndReturn(run func(ctx context.Context, token string) *AuthClaims) *MockService_GetSession_Call {
	_c.Call.Return(run)
	return _c
}

// NewSession provides a mock function for the type MockService
func (_mock *MockService) NewSession(ctx context.Context, data *AuthClaims, validForDuration time.Duration) (string, error) {
	ret := _mock.Called(ctx, data, validForDuration)

	if len(ret) == 0 {
		panic("no return value specified for NewSession")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *AuthClaims, time.Duration) (string, error)); ok {
		return returnFunc(ctx, data, validForDuration)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *AuthClaims, time.Duration) string); ok {
		r0 = returnFunc(ctx, data, validForDuration)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *AuthClaims, time.Duration) error); ok {
		r1 = returnFunc(ctx, data, validForDuration)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_NewSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewSession'
type MockService_NewSession_Call struct {
	*mock.Call
}

// NewSession is a helper method to define mock.On call
//   - ctx context.Context
//   - data *AuthClaims
//   - validForDuration time.Duration
func (_e *MockService_Expecter) NewSession(ctx interface{}, data interface{}, validForDuration interface{}) *MockService_NewSession_Call {
	return &MockService_NewSession_Call{Call: _e.mock.On("NewSession", ctx, data, validForDuration)}
}

func (_c *MockService_NewSession_Call) Run(run func(ctx context.Context, data *AuthClaims, validForDuration time.Duration)) *MockService_NewSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *AuthClaims
		if args[1] != nil {
			arg1 = args[1].(*AuthClaims)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_NewSession_Call) Return(s string, err error) *MockService_NewSession_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockService_NewSession_Call) RunAndReturn(run func(ctx context.Context, data *AuthClaims, validForDuration time.Duration) (string, error)) *MockService_NewSession_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveSession provides a mock function for the type MockService
func (_mock *MockService) RemoveSession(ctx context.Context, token string) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for RemoveSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_RemoveSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveSession'
type MockService_RemoveSession_Call struct {
	*mock.Call
}

// RemoveSession is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockService_Expecter) RemoveSession(ctx interface{}, token interface{}) *MockService_RemoveSession_Call {
	return &MockService_RemoveSession_Call{Call: _e.mock.On("RemoveSession", ctx, token)}
}

func (_c *MockService_RemoveSession_Call) Run(run func(ctx context.Context, token string)) *MockService_RemoveSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_RemoveSession_Call) Return(err error) *MockService_RemoveSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_RemoveSession_Call) RunAndReturn(run func(ctx context.Context, token string) error) *MockService_RemoveSession_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockStorage
func (_mock *MockStorage) Get(ctx context.Context, token string) (*AuthClaims, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *AuthClaims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*AuthClaims, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *AuthClaims); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*AuthClaims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockStorage_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockStorage_Expecter) Get(ctx interface{}, token interface{}) *MockStorage_Get_Call {
	return &MockStorage_Get_Call{Call: _e.mock.On("Get", ctx, token)}
}

func (_c *MockStorage_Get_Call) Run(run func(ctx context.Context, token string)) *MockStorage_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_Get_Call) Return(authClaims *AuthClaims, err error) *MockStorage_Get_Call {
	_c.Call.Return(authClaims, err)
	return _c
}

func (_c *MockStorage_Get_Call) RunAndReturn(run func(ctx context.Context, token string) (*AuthClaims, error)) *MockStorage_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type MockStorage
func (_mock *MockStorage) Remove(ctx context.Context, token string) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockStorage_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockStorage_Expecter) Remove(ctx interface{}, token interface{}) *MockStorage_Remove_Call {
	return &MockStorage_Remove_Call{Call: _e.mock.On("Remove", ctx, token)}
}

func (_c *MockStorage_Remove_Call) Run(run func(ctx context.Context, token string)) *MockStorage_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_Remove_Call) Return(err error) *MockStorage_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_Remove_Call) RunAndReturn(run func(ctx context.Context, token string) error) *MockStorage_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockStorage
func (_mock *MockStorage) Set(ctx context.Context, token string, claims *AuthClaims, expiresAt time.Time) error {
	ret := _mock.Called(ctx, token, claims, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *AuthClaims, time.Time) error); ok {
		r0 = returnFunc(ctx, token, claims, expiresAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockStorage_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - claims *AuthClaims
//   - expiresAt time.Time
func (_e *MockStorage_Expecter) Set(ctx interface{}, token interface{}, claims interface{}, expiresAt interface{}) *MockStorage_Set_Call {
	return &MockStorage_Set_Call{Call: _e.mock.On("Set", ctx, token, claims, expiresAt)}
}

func (_c *MockStorage_Set_Call) Run(run func(ctx context.Context, token string, claims *AuthClaims, expiresAt time.Time)) *MockStorage_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *AuthClaims
		if args[2] != nil {
			arg2 = args[2].(*AuthClaims)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStorage_Set_Call) Return(err error) *MockStorage_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_Set_Call) RunAndReturn(run func(ctx context.Context, token string, claims *AuthClaims, expiresAt time.Time) error) *MockStorage_Set_Call {
	_c.Call.Return(run)
	return _c
}
