// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package actions

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// SendOTPByEmail provides a mock function for the type MockService
func (_mock *MockService) SendOTPByEmail(ctx context.Context, code string, toEmail string) {
	_mock.Called(ctx, code, toEmail)
	return
}

// MockService_SendOTPByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendOTPByEmail'
type MockService_SendOTPByEmail_Call struct {
	*mock.Call
}

// SendOTPByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
//   - toEmail string
func (_e *MockService_Expecter) SendOTPByEmail(ctx interface{}, code interface{}, toEmail interface{}) *MockService_SendOTPByEmail_Call {
	return &MockService_SendOTPByEmail_Call{Call: _e.mock.On("SendOTPByEmail", ctx, code, toEmail)}
}

func (_c *MockService_SendOTPByEmail_Call) Run(run func(ctx context.Context, code string, toEmail string)) *MockService_SendOTPByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_SendOTPByEmail_Call) Return() *MockService_SendOTPByEmail_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_SendOTPByEmail_Call) RunAndReturn(run func(ctx context.Context, code string, toEmail string)) *MockService_SendOTPByEmail_Call {
	_c.Run(run)
	return _c
}
