all: false
dir: '{{.InterfaceDir}}'
filename: mocks.go
force-file-write: true
formatter: goimports
log-level: info
structname: '{{.Mock}}{{.InterfaceName}}'
pkgname: '{{.SrcPackageName}}'
recursive: false
require-template-schema-exists: true
template: testify
template-schema: '{{.Template}}.schema.json'
packages:
  github.com/zeusito/toci/internal:
    config:
      all: true
      recursive: true
  github.com/zeusito/toci/pkg/security:
    config:
      all: true
      recursive: true
  github.com/zeusito/toci/pkg/toolbox:
    config:
      all: true
      recursive: true
