// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package otp

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockManager creates a new instance of MockManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManager {
	mock := &MockManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockManager is an autogenerated mock type for the Manager type
type MockManager struct {
	mock.Mock
}

type MockManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManager) EXPECT() *MockManager_Expecter {
	return &MockManager_Expecter{mock: &_m.Mock}
}

// GenerateOTP provides a mock function for the type MockManager
func (_mock *MockManager) GenerateOTP(ctx context.Context, length int, kind Kind) (OneTimePassword, bool) {
	ret := _mock.Called(ctx, length, kind)

	if len(ret) == 0 {
		panic("no return value specified for GenerateOTP")
	}

	var r0 OneTimePassword
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, Kind) (OneTimePassword, bool)); ok {
		return returnFunc(ctx, length, kind)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, Kind) OneTimePassword); ok {
		r0 = returnFunc(ctx, length, kind)
	} else {
		r0 = ret.Get(0).(OneTimePassword)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, Kind) bool); ok {
		r1 = returnFunc(ctx, length, kind)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockManager_GenerateOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateOTP'
type MockManager_GenerateOTP_Call struct {
	*mock.Call
}

// GenerateOTP is a helper method to define mock.On call
//   - ctx context.Context
//   - length int
//   - kind Kind
func (_e *MockManager_Expecter) GenerateOTP(ctx interface{}, length interface{}, kind interface{}) *MockManager_GenerateOTP_Call {
	return &MockManager_GenerateOTP_Call{Call: _e.mock.On("GenerateOTP", ctx, length, kind)}
}

func (_c *MockManager_GenerateOTP_Call) Run(run func(ctx context.Context, length int, kind Kind)) *MockManager_GenerateOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 Kind
		if args[2] != nil {
			arg2 = args[2].(Kind)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockManager_GenerateOTP_Call) Return(oneTimePassword OneTimePassword, b bool) *MockManager_GenerateOTP_Call {
	_c.Call.Return(oneTimePassword, b)
	return _c
}

func (_c *MockManager_GenerateOTP_Call) RunAndReturn(run func(ctx context.Context, length int, kind Kind) (OneTimePassword, bool)) *MockManager_GenerateOTP_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type MockManager
func (_mock *MockManager) Remove(ctx context.Context, code string) bool {
	ret := _mock.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, code)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockManager_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockManager_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *MockManager_Expecter) Remove(ctx interface{}, code interface{}) *MockManager_Remove_Call {
	return &MockManager_Remove_Call{Call: _e.mock.On("Remove", ctx, code)}
}

func (_c *MockManager_Remove_Call) Run(run func(ctx context.Context, code string)) *MockManager_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockManager_Remove_Call) Return(b bool) *MockManager_Remove_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockManager_Remove_Call) RunAndReturn(run func(ctx context.Context, code string) bool) *MockManager_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// Retrieve provides a mock function for the type MockManager
func (_mock *MockManager) Retrieve(ctx context.Context, kind Kind, code string) (OneTimePassword, bool) {
	ret := _mock.Called(ctx, kind, code)

	if len(ret) == 0 {
		panic("no return value specified for Retrieve")
	}

	var r0 OneTimePassword
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, Kind, string) (OneTimePassword, bool)); ok {
		return returnFunc(ctx, kind, code)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, Kind, string) OneTimePassword); ok {
		r0 = returnFunc(ctx, kind, code)
	} else {
		r0 = ret.Get(0).(OneTimePassword)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, Kind, string) bool); ok {
		r1 = returnFunc(ctx, kind, code)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockManager_Retrieve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Retrieve'
type MockManager_Retrieve_Call struct {
	*mock.Call
}

// Retrieve is a helper method to define mock.On call
//   - ctx context.Context
//   - kind Kind
//   - code string
func (_e *MockManager_Expecter) Retrieve(ctx interface{}, kind interface{}, code interface{}) *MockManager_Retrieve_Call {
	return &MockManager_Retrieve_Call{Call: _e.mock.On("Retrieve", ctx, kind, code)}
}

func (_c *MockManager_Retrieve_Call) Run(run func(ctx context.Context, kind Kind, code string)) *MockManager_Retrieve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Kind
		if args[1] != nil {
			arg1 = args[1].(Kind)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockManager_Retrieve_Call) Return(oneTimePassword OneTimePassword, b bool) *MockManager_Retrieve_Call {
	_c.Call.Return(oneTimePassword, b)
	return _c
}

func (_c *MockManager_Retrieve_Call) RunAndReturn(run func(ctx context.Context, kind Kind, code string) (OneTimePassword, bool)) *MockManager_Retrieve_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockStorage
func (_mock *MockStorage) Get(ctx context.Context, kind Kind, hashedCode string) (OneTimePassword, error) {
	ret := _mock.Called(ctx, kind, hashedCode)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 OneTimePassword
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Kind, string) (OneTimePassword, error)); ok {
		return returnFunc(ctx, kind, hashedCode)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, Kind, string) OneTimePassword); ok {
		r0 = returnFunc(ctx, kind, hashedCode)
	} else {
		r0 = ret.Get(0).(OneTimePassword)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, Kind, string) error); ok {
		r1 = returnFunc(ctx, kind, hashedCode)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockStorage_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - kind Kind
//   - hashedCode string
func (_e *MockStorage_Expecter) Get(ctx interface{}, kind interface{}, hashedCode interface{}) *MockStorage_Get_Call {
	return &MockStorage_Get_Call{Call: _e.mock.On("Get", ctx, kind, hashedCode)}
}

func (_c *MockStorage_Get_Call) Run(run func(ctx context.Context, kind Kind, hashedCode string)) *MockStorage_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Kind
		if args[1] != nil {
			arg1 = args[1].(Kind)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorage_Get_Call) Return(oneTimePassword OneTimePassword, err error) *MockStorage_Get_Call {
	_c.Call.Return(oneTimePassword, err)
	return _c
}

func (_c *MockStorage_Get_Call) RunAndReturn(run func(ctx context.Context, kind Kind, hashedCode string) (OneTimePassword, error)) *MockStorage_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function for the type MockStorage
func (_mock *MockStorage) Put(ctx context.Context, data OneTimePassword, expiresAt time.Time) error {
	ret := _mock.Called(ctx, data, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, OneTimePassword, time.Time) error); ok {
		r0 = returnFunc(ctx, data, expiresAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type MockStorage_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - ctx context.Context
//   - data OneTimePassword
//   - expiresAt time.Time
func (_e *MockStorage_Expecter) Put(ctx interface{}, data interface{}, expiresAt interface{}) *MockStorage_Put_Call {
	return &MockStorage_Put_Call{Call: _e.mock.On("Put", ctx, data, expiresAt)}
}

func (_c *MockStorage_Put_Call) Run(run func(ctx context.Context, data OneTimePassword, expiresAt time.Time)) *MockStorage_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 OneTimePassword
		if args[1] != nil {
			arg1 = args[1].(OneTimePassword)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorage_Put_Call) Return(err error) *MockStorage_Put_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_Put_Call) RunAndReturn(run func(ctx context.Context, data OneTimePassword, expiresAt time.Time) error) *MockStorage_Put_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type MockStorage
func (_mock *MockStorage) Remove(ctx context.Context, hashedCode string) error {
	ret := _mock.Called(ctx, hashedCode)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, hashedCode)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockStorage_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
//   - hashedCode string
func (_e *MockStorage_Expecter) Remove(ctx interface{}, hashedCode interface{}) *MockStorage_Remove_Call {
	return &MockStorage_Remove_Call{Call: _e.mock.On("Remove", ctx, hashedCode)}
}

func (_c *MockStorage_Remove_Call) Run(run func(ctx context.Context, hashedCode string)) *MockStorage_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_Remove_Call) Return(err error) *MockStorage_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_Remove_Call) RunAndReturn(run func(ctx context.Context, hashedCode string) error) *MockStorage_Remove_Call {
	_c.Call.Return(run)
	return _c
}
