// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package otp

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockManager creates a new instance of MockManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManager {
	mock := &MockManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockManager is an autogenerated mock type for the Manager type
type MockManager struct {
	mock.Mock
}

type MockManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManager) EXPECT() *MockManager_Expecter {
	return &MockManager_Expecter{mock: &_m.Mock}
}

// GenerateCode provides a mock function for the type MockManager
func (_mock *MockManager) GenerateCode(ctx context.Context, length int, kind Kind, principal string) (string, bool) {
	ret := _mock.Called(ctx, length, kind, principal)

	if len(ret) == 0 {
		panic("no return value specified for GenerateCode")
	}

	var r0 string
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, Kind, string) (string, bool)); ok {
		return returnFunc(ctx, length, kind, principal)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, Kind, string) string); ok {
		r0 = returnFunc(ctx, length, kind, principal)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, Kind, string) bool); ok {
		r1 = returnFunc(ctx, length, kind, principal)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockManager_GenerateCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateCode'
type MockManager_GenerateCode_Call struct {
	*mock.Call
}

// GenerateCode is a helper method to define mock.On call
//   - ctx context.Context
//   - length int
//   - kind Kind
//   - principal string
func (_e *MockManager_Expecter) GenerateCode(ctx interface{}, length interface{}, kind interface{}, principal interface{}) *MockManager_GenerateCode_Call {
	return &MockManager_GenerateCode_Call{Call: _e.mock.On("GenerateCode", ctx, length, kind, principal)}
}

func (_c *MockManager_GenerateCode_Call) Run(run func(ctx context.Context, length int, kind Kind, principal string)) *MockManager_GenerateCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 Kind
		if args[2] != nil {
			arg2 = args[2].(Kind)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockManager_GenerateCode_Call) Return(s string, b bool) *MockManager_GenerateCode_Call {
	_c.Call.Return(s, b)
	return _c
}

func (_c *MockManager_GenerateCode_Call) RunAndReturn(run func(ctx context.Context, length int, kind Kind, principal string) (string, bool)) *MockManager_GenerateCode_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type MockManager
func (_mock *MockManager) Remove(ctx context.Context, kind Kind, principal string) bool {
	ret := _mock.Called(ctx, kind, principal)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, Kind, string) bool); ok {
		r0 = returnFunc(ctx, kind, principal)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockManager_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockManager_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
//   - kind Kind
//   - principal string
func (_e *MockManager_Expecter) Remove(ctx interface{}, kind interface{}, principal interface{}) *MockManager_Remove_Call {
	return &MockManager_Remove_Call{Call: _e.mock.On("Remove", ctx, kind, principal)}
}

func (_c *MockManager_Remove_Call) Run(run func(ctx context.Context, kind Kind, principal string)) *MockManager_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Kind
		if args[1] != nil {
			arg1 = args[1].(Kind)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockManager_Remove_Call) Return(b bool) *MockManager_Remove_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockManager_Remove_Call) RunAndReturn(run func(ctx context.Context, kind Kind, principal string) bool) *MockManager_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyCode provides a mock function for the type MockManager
func (_mock *MockManager) VerifyCode(ctx context.Context, kind Kind, principal string, code string) bool {
	ret := _mock.Called(ctx, kind, principal, code)

	if len(ret) == 0 {
		panic("no return value specified for VerifyCode")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, Kind, string, string) bool); ok {
		r0 = returnFunc(ctx, kind, principal, code)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockManager_VerifyCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyCode'
type MockManager_VerifyCode_Call struct {
	*mock.Call
}

// VerifyCode is a helper method to define mock.On call
//   - ctx context.Context
//   - kind Kind
//   - principal string
//   - code string
func (_e *MockManager_Expecter) VerifyCode(ctx interface{}, kind interface{}, principal interface{}, code interface{}) *MockManager_VerifyCode_Call {
	return &MockManager_VerifyCode_Call{Call: _e.mock.On("VerifyCode", ctx, kind, principal, code)}
}

func (_c *MockManager_VerifyCode_Call) Run(run func(ctx context.Context, kind Kind, principal string, code string)) *MockManager_VerifyCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Kind
		if args[1] != nil {
			arg1 = args[1].(Kind)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockManager_VerifyCode_Call) Return(b bool) *MockManager_VerifyCode_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockManager_VerifyCode_Call) RunAndReturn(run func(ctx context.Context, kind Kind, principal string, code string) bool) *MockManager_VerifyCode_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockStorage
func (_mock *MockStorage) Get(ctx context.Context, kind Kind, principal string) (*otpData, error) {
	ret := _mock.Called(ctx, kind, principal)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *otpData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Kind, string) (*otpData, error)); ok {
		return returnFunc(ctx, kind, principal)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, Kind, string) *otpData); ok {
		r0 = returnFunc(ctx, kind, principal)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*otpData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, Kind, string) error); ok {
		r1 = returnFunc(ctx, kind, principal)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockStorage_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - kind Kind
//   - principal string
func (_e *MockStorage_Expecter) Get(ctx interface{}, kind interface{}, principal interface{}) *MockStorage_Get_Call {
	return &MockStorage_Get_Call{Call: _e.mock.On("Get", ctx, kind, principal)}
}

func (_c *MockStorage_Get_Call) Run(run func(ctx context.Context, kind Kind, principal string)) *MockStorage_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Kind
		if args[1] != nil {
			arg1 = args[1].(Kind)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorage_Get_Call) Return(otpDataMoqParam *otpData, err error) *MockStorage_Get_Call {
	_c.Call.Return(otpDataMoqParam, err)
	return _c
}

func (_c *MockStorage_Get_Call) RunAndReturn(run func(ctx context.Context, kind Kind, principal string) (*otpData, error)) *MockStorage_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function for the type MockStorage
func (_mock *MockStorage) Put(ctx context.Context, kind Kind, principal string, hashedCode string, expiresAt time.Time) error {
	ret := _mock.Called(ctx, kind, principal, hashedCode, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Kind, string, string, time.Time) error); ok {
		r0 = returnFunc(ctx, kind, principal, hashedCode, expiresAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type MockStorage_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - ctx context.Context
//   - kind Kind
//   - principal string
//   - hashedCode string
//   - expiresAt time.Time
func (_e *MockStorage_Expecter) Put(ctx interface{}, kind interface{}, principal interface{}, hashedCode interface{}, expiresAt interface{}) *MockStorage_Put_Call {
	return &MockStorage_Put_Call{Call: _e.mock.On("Put", ctx, kind, principal, hashedCode, expiresAt)}
}

func (_c *MockStorage_Put_Call) Run(run func(ctx context.Context, kind Kind, principal string, hashedCode string, expiresAt time.Time)) *MockStorage_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Kind
		if args[1] != nil {
			arg1 = args[1].(Kind)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockStorage_Put_Call) Return(err error) *MockStorage_Put_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_Put_Call) RunAndReturn(run func(ctx context.Context, kind Kind, principal string, hashedCode string, expiresAt time.Time) error) *MockStorage_Put_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type MockStorage
func (_mock *MockStorage) Remove(ctx context.Context, kind Kind, principal string) error {
	ret := _mock.Called(ctx, kind, principal)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Kind, string) error); ok {
		r0 = returnFunc(ctx, kind, principal)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockStorage_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
//   - kind Kind
//   - principal string
func (_e *MockStorage_Expecter) Remove(ctx interface{}, kind interface{}, principal interface{}) *MockStorage_Remove_Call {
	return &MockStorage_Remove_Call{Call: _e.mock.On("Remove", ctx, kind, principal)}
}

func (_c *MockStorage_Remove_Call) Run(run func(ctx context.Context, kind Kind, principal string)) *MockStorage_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Kind
		if args[1] != nil {
			arg1 = args[1].(Kind)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorage_Remove_Call) Return(err error) *MockStorage_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_Remove_Call) RunAndReturn(run func(ctx context.Context, kind Kind, principal string) error) *MockStorage_Remove_Call {
	_c.Call.Return(run)
	return _c
}
