// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package signin

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/zeusito/toci/internal/dbmodels"
)

// NewMockRepo creates a new instance of MockRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepo {
	mock := &MockRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepo is an autogenerated mock type for the Repo type
type MockRepo struct {
	mock.Mock
}

type MockRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepo) EXPECT() *MockRepo_Expecter {
	return &MockRepo_Expecter{mock: &_m.Mock}
}

// FindOneByEmail provides a mock function for the type MockRepo
func (_mock *MockRepo) FindOneByEmail(ctx context.Context, email string) (*dbmodels.IdentityRecord, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindOneByEmail")
	}

	var r0 *dbmodels.IdentityRecord
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*dbmodels.IdentityRecord, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *dbmodels.IdentityRecord); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dbmodels.IdentityRecord)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepo_FindOneByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOneByEmail'
type MockRepo_FindOneByEmail_Call struct {
	*mock.Call
}

// FindOneByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockRepo_Expecter) FindOneByEmail(ctx interface{}, email interface{}) *MockRepo_FindOneByEmail_Call {
	return &MockRepo_FindOneByEmail_Call{Call: _e.mock.On("FindOneByEmail", ctx, email)}
}

func (_c *MockRepo_FindOneByEmail_Call) Run(run func(ctx context.Context, email string)) *MockRepo_FindOneByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepo_FindOneByEmail_Call) Return(identityRecord *dbmodels.IdentityRecord, err error) *MockRepo_FindOneByEmail_Call {
	_c.Call.Return(identityRecord, err)
	return _c
}

func (_c *MockRepo_FindOneByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*dbmodels.IdentityRecord, error)) *MockRepo_FindOneByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// SignInWithEmailOTP provides a mock function for the type MockService
func (_mock *MockService) SignInWithEmailOTP(ctx context.Context, email string, source string) error {
	ret := _mock.Called(ctx, email, source)

	if len(ret) == 0 {
		panic("no return value specified for SignInWithEmailOTP")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, email, source)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_SignInWithEmailOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignInWithEmailOTP'
type MockService_SignInWithEmailOTP_Call struct {
	*mock.Call
}

// SignInWithEmailOTP is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - source string
func (_e *MockService_Expecter) SignInWithEmailOTP(ctx interface{}, email interface{}, source interface{}) *MockService_SignInWithEmailOTP_Call {
	return &MockService_SignInWithEmailOTP_Call{Call: _e.mock.On("SignInWithEmailOTP", ctx, email, source)}
}

func (_c *MockService_SignInWithEmailOTP_Call) Run(run func(ctx context.Context, email string, source string)) *MockService_SignInWithEmailOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_SignInWithEmailOTP_Call) Return(err error) *MockService_SignInWithEmailOTP_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_SignInWithEmailOTP_Call) RunAndReturn(run func(ctx context.Context, email string, source string) error) *MockService_SignInWithEmailOTP_Call {
	_c.Call.Return(run)
	return _c
}

// SignInWithOpenID provides a mock function for the type MockService
func (_mock *MockService) SignInWithOpenID(ctx context.Context, provider string, token string, source string) (*SignInResponse, error) {
	ret := _mock.Called(ctx, provider, token, source)

	if len(ret) == 0 {
		panic("no return value specified for SignInWithOpenID")
	}

	var r0 *SignInResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*SignInResponse, error)); ok {
		return returnFunc(ctx, provider, token, source)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *SignInResponse); ok {
		r0 = returnFunc(ctx, provider, token, source)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*SignInResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, provider, token, source)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_SignInWithOpenID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignInWithOpenID'
type MockService_SignInWithOpenID_Call struct {
	*mock.Call
}

// SignInWithOpenID is a helper method to define mock.On call
//   - ctx context.Context
//   - provider string
//   - token string
//   - source string
func (_e *MockService_Expecter) SignInWithOpenID(ctx interface{}, provider interface{}, token interface{}, source interface{}) *MockService_SignInWithOpenID_Call {
	return &MockService_SignInWithOpenID_Call{Call: _e.mock.On("SignInWithOpenID", ctx, provider, token, source)}
}

func (_c *MockService_SignInWithOpenID_Call) Run(run func(ctx context.Context, provider string, token string, source string)) *MockService_SignInWithOpenID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_SignInWithOpenID_Call) Return(signInResponse *SignInResponse, err error) *MockService_SignInWithOpenID_Call {
	_c.Call.Return(signInResponse, err)
	return _c
}

func (_c *MockService_SignInWithOpenID_Call) RunAndReturn(run func(ctx context.Context, provider string, token string, source string) (*SignInResponse, error)) *MockService_SignInWithOpenID_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyEmailOTP provides a mock function for the type MockService
func (_mock *MockService) VerifyEmailOTP(ctx context.Context, code string, email string) (*SignInResponse, error) {
	ret := _mock.Called(ctx, code, email)

	if len(ret) == 0 {
		panic("no return value specified for VerifyEmailOTP")
	}

	var r0 *SignInResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*SignInResponse, error)); ok {
		return returnFunc(ctx, code, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *SignInResponse); ok {
		r0 = returnFunc(ctx, code, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*SignInResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, code, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_VerifyEmailOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyEmailOTP'
type MockService_VerifyEmailOTP_Call struct {
	*mock.Call
}

// VerifyEmailOTP is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
//   - email string
func (_e *MockService_Expecter) VerifyEmailOTP(ctx interface{}, code interface{}, email interface{}) *MockService_VerifyEmailOTP_Call {
	return &MockService_VerifyEmailOTP_Call{Call: _e.mock.On("VerifyEmailOTP", ctx, code, email)}
}

func (_c *MockService_VerifyEmailOTP_Call) Run(run func(ctx context.Context, code string, email string)) *MockService_VerifyEmailOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_VerifyEmailOTP_Call) Return(signInResponse *SignInResponse, err error) *MockService_VerifyEmailOTP_Call {
	_c.Call.Return(signInResponse, err)
	return _c
}

func (_c *MockService_VerifyEmailOTP_Call) RunAndReturn(run func(ctx context.Context, code string, email string) (*SignInResponse, error)) *MockService_VerifyEmailOTP_Call {
	_c.Call.Return(run)
	return _c
}
